# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de05003295a0018bc65fafabbe1994b5b76f572ef1a208bdb6ec6612275d44c0809188b8d90c024380f5cf46ced205bfb115d95d3e9bba58f6950f1359a91b0f

test:
  secret_key_base: 0b685f057a0daa52c0ea6abc9d025ddac2c5f15ed85e7b18cef778f7bca62664cc13cff299d2da85e674bc9b7eea5e63ed1585cb5cdab3616275f85f2cd87c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
